import { Exercise, MuscleGroup } from '../models/exercise.model';

export const EXERCISE_TREE: Exercise[] = [
  {
    id: 'pecho-1',
    name: 'Flexiones de Rodillas',
    description: 'Flexiones básicas apoyando las rodillas. Ideal para principiantes.',
    level: 1,
    xpReward: 10,
    muscleGroup: MuscleGroup.PECHO,
    sets: 3,
    reps: '8-10',
    restTime: 60,
    unlocked: true,
    completed: false
  },
  {
    id: 'pecho-2',
    name: 'Flexiones Estándar',
    description: 'Flexiones clásicas con el cuerpo recto.',
    level: 2,
    xpReward: 20,
    prerequisites: ['pecho-1'],
    muscleGroup: MuscleGroup.PECHO,
    sets: 3,
    reps: '10-15',
    restTime: 60,
    unlocked: false,
    completed: false
  },
  {
    id: 'pecho-3',
    name: 'Flexiones Diamante',
    description: 'Flexiones con las manos juntas formando un diamante.',
    level: 3,
    xpReward: 35,
    prerequisites: ['pecho-2'],
    muscleGroup: MuscleGroup.PECHO,
    sets: 3,
    reps: '8-12',
    restTime: 90,
    unlocked: false,
    completed: false
  },
  {
    id: 'pecho-4',
    name: 'Flexiones Explosivas',
    description: 'Flexiones con impulso, despegando las manos del suelo.',
    level: 4,
    xpReward: 50,
    prerequisites: ['pecho-3'],
    muscleGroup: MuscleGroup.PECHO,
    sets: 3,
    reps: '5-8',
    restTime: 120,
    unlocked: false,
    completed: false
  },

  {
    id: 'espalda-1',
    name: 'Superman',
    description: 'Acostado boca abajo, elevar brazos y piernas simultáneamente.',
    level: 1,
    xpReward: 10,
    muscleGroup: MuscleGroup.ESPALDA,
    sets: 3,
    reps: '10-12',
    restTime: 45,
    unlocked: true,
    completed: false
  },
  {
    id: 'espalda-2',
    name: 'Remo Invertido (Mesa)',
    description: 'Usando una mesa, realizar remo con el peso corporal.',
    level: 2,
    xpReward: 20,
    prerequisites: ['espalda-1'],
    muscleGroup: MuscleGroup.ESPALDA,
    sets: 3,
    reps: '8-12',
    restTime: 60,
    unlocked: false,
    completed: false
  },
  {
    id: 'espalda-3',
    name: 'Dominadas Asistidas',
    description: 'Dominadas con ayuda de banda elástica o pie apoyado.',
    level: 3,
    xpReward: 35,
    prerequisites: ['espalda-2'],
    muscleGroup: MuscleGroup.ESPALDA,
    sets: 3,
    reps: '5-8',
    restTime: 90,
    unlocked: false,
    completed: false
  },
  {
    id: 'espalda-4',
    name: 'Dominadas Completas',
    description: 'Dominadas sin asistencia, subiendo la barbilla sobre la barra.',
    level: 4,
    xpReward: 50,
    prerequisites: ['espalda-3'],
    muscleGroup: MuscleGroup.ESPALDA,
    sets: 3,
    reps: '5-10',
    restTime: 120,
    unlocked: false,
    completed: false
  },

  {
    id: 'piernas-1',
    name: 'Sentadillas Básicas',
    description: 'Sentadillas con peso corporal, pies al ancho de hombros.',
    level: 1,
    xpReward: 10,
    muscleGroup: MuscleGroup.PIERNAS,
    sets: 3,
    reps: '12-15',
    restTime: 60,
    unlocked: true,
    completed: false
  },
  {
    id: 'piernas-2',
    name: 'Zancadas Alternas',
    description: 'Paso adelante, bajando la rodilla trasera hacia el suelo.',
    level: 2,
    xpReward: 20,
    prerequisites: ['piernas-1'],
    muscleGroup: MuscleGroup.PIERNAS,
    sets: 3,
    reps: '10-12 por pierna',
    restTime: 60,
    unlocked: false,
    completed: false
  },
  {
    id: 'piernas-3',
    name: 'Sentadilla Pistol Asistida',
    description: 'Sentadilla a una pierna con apoyo.',
    level: 3,
    xpReward: 35,
    prerequisites: ['piernas-2'],
    muscleGroup: MuscleGroup.PIERNAS,
    sets: 3,
    reps: '5-8 por pierna',
    restTime: 90,
    unlocked: false,
    completed: false
  },
  {
    id: 'piernas-4',
    name: 'Sentadilla Pistol',
    description: 'Sentadilla completa a una sola pierna sin apoyo.',
    level: 4,
    xpReward: 50,
    prerequisites: ['piernas-3'],
    muscleGroup: MuscleGroup.PIERNAS,
    sets: 3,
    reps: '5-8 por pierna',
    restTime: 120,
    unlocked: false,
    completed: false
  },

  {
    id: 'hombros-1',
    name: 'Elevaciones Laterales (Sin peso)',
    description: 'Brazos extendidos a los lados, subir hasta altura de hombros.',
    level: 1,
    xpReward: 10,
    muscleGroup: MuscleGroup.HOMBROS,
    sets: 3,
    reps: '12-15',
    restTime: 45,
    unlocked: true,
    completed: false
  },
  {
    id: 'hombros-2',
    name: 'Pike Push-ups',
    description: 'Flexiones en V invertida, enfocando los hombros.',
    level: 2,
    xpReward: 20,
    prerequisites: ['hombros-1'],
    muscleGroup: MuscleGroup.HOMBROS,
    sets: 3,
    reps: '8-12',
    restTime: 60,
    unlocked: false,
    completed: false
  },
  {
    id: 'hombros-3',
    name: 'Flexiones Verticales Asistidas',
    description: 'Parada de manos contra la pared, bajando la cabeza.',
    level: 3,
    xpReward: 35,
    prerequisites: ['hombros-2'],
    muscleGroup: MuscleGroup.HOMBROS,
    sets: 3,
    reps: '5-8',
    restTime: 90,
    unlocked: false,
    completed: false
  },
  {
    id: 'hombros-4',
    name: 'Flexiones Verticales Completas',
    description: 'Parada de manos libre con flexiones.',
    level: 4,
    xpReward: 50,
    prerequisites: ['hombros-3'],
    muscleGroup: MuscleGroup.HOMBROS,
    sets: 3,
    reps: '3-6',
    restTime: 120,
    unlocked: false,
    completed: false
  },

  {
    id: 'brazos-1',
    name: 'Fondos en Silla',
    description: 'Fondos de tríceps usando una silla.',
    level: 1,
    xpReward: 10,
    muscleGroup: MuscleGroup.BRAZOS,
    sets: 3,
    reps: '10-15',
    restTime: 45,
    unlocked: true,
    completed: false
  },
  {
    id: 'brazos-2',
    name: 'Curl de Bíceps Isométrico',
    description: 'Mantener tensión en posición de curl.',
    level: 2,
    xpReward: 20,
    prerequisites: ['brazos-1'],
    muscleGroup: MuscleGroup.BRAZOS,
    sets: 3,
    reps: '30 seg',
    restTime: 60,
    unlocked: false,
    completed: false
  },
  {
    id: 'brazos-3',
    name: 'Fondos en Paralelas',
    description: 'Fondos completos usando barras paralelas.',
    level: 3,
    xpReward: 35,
    prerequisites: ['brazos-2'],
    muscleGroup: MuscleGroup.BRAZOS,
    sets: 3,
    reps: '8-12',
    restTime: 90,
    unlocked: false,
    completed: false
  },
  {
    id: 'brazos-4',
    name: 'Dominadas Supinas',
    description: 'Dominadas con agarre supino para enfatizar bíceps.',
    level: 4,
    xpReward: 50,
    prerequisites: ['brazos-3'],
    muscleGroup: MuscleGroup.BRAZOS,
    sets: 3,
    reps: '6-10',
    restTime: 120,
    unlocked: false,
    completed: false
  },

  {
    id: 'core-1',
    name: 'Plancha Básica',
    description: 'Mantener posición de plancha sobre antebrazos.',
    level: 1,
    xpReward: 10,
    muscleGroup: MuscleGroup.CORE,
    sets: 3,
    reps: '30-45 seg',
    restTime: 45,
    unlocked: true,
    completed: false
  },
  {
    id: 'core-2',
    name: 'Crunch Abdominal',
    description: 'Elevación de tronco enfocando abdominales.',
    level: 2,
    xpReward: 20,
    prerequisites: ['core-1'],
    muscleGroup: MuscleGroup.CORE,
    sets: 3,
    reps: '15-20',
    restTime: 45,
    unlocked: false,
    completed: false
  },
  {
    id: 'core-3',
    name: 'Elevación de Piernas',
    description: 'Acostado, elevar piernas hasta 90 grados.',
    level: 3,
    xpReward: 35,
    prerequisites: ['core-2'],
    muscleGroup: MuscleGroup.CORE,
    sets: 3,
    reps: '12-15',
    restTime: 60,
    unlocked: false,
    completed: false
  },
  {
    id: 'core-4',
    name: 'Dragon Flag',
    description: 'Ejercicio avanzado de core, cuerpo recto elevado.',
    level: 4,
    xpReward: 50,
    prerequisites: ['core-3'],
    muscleGroup: MuscleGroup.CORE,
    sets: 3,
    reps: '5-8',
    restTime: 90,
    unlocked: false,
    completed: false
  },

  {
    id: 'cardio-1',
    name: 'Marcha en Sitio',
    description: 'Marchar levantando rodillas durante tiempo establecido.',
    level: 1,
    xpReward: 10,
    muscleGroup: MuscleGroup.CARDIO,
    sets: 3,
    reps: '1 min',
    restTime: 60,
    unlocked: true,
    completed: false
  },
  {
    id: 'cardio-2',
    name: 'Jumping Jacks',
    description: 'Saltos abriendo y cerrando piernas y brazos.',
    level: 2,
    xpReward: 20,
    prerequisites: ['cardio-1'],
    muscleGroup: MuscleGroup.CARDIO,
    sets: 3,
    reps: '30 seg',
    restTime: 45,
    unlocked: false,
    completed: false
  },
  {
    id: 'cardio-3',
    name: 'Burpees',
    description: 'Ejercicio completo: sentadilla, plancha, flexión y salto.',
    level: 3,
    xpReward: 35,
    prerequisites: ['cardio-2'],
    muscleGroup: MuscleGroup.CARDIO,
    sets: 3,
    reps: '10-15',
    restTime: 60,
    unlocked: false,
    completed: false
  },
  {
    id: 'cardio-4',
    name: 'Burpees con Flexión',
    description: 'Burpees añadiendo flexión completa en cada repetición.',
    level: 4,
    xpReward: 50,
    prerequisites: ['cardio-3'],
    muscleGroup: MuscleGroup.CARDIO,
    sets: 3,
    reps: '10-12',
    restTime: 90,
    unlocked: false,
    completed: false
  }
];
